version: "3.4"

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    depends_on:
      - "sqlserver"
      - "webapi"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - "sqlserver"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    shm_size: 1gb
    volumes:
      - mssql22:/var/opt/mssql
    ports:
      - "1434:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U "sa" -P "$$MSSQL_SA_PASSWORD" -Q "select 1" -b
      start_period: 1m
      start_interval: 1s
      timeout: 10s
      interval: 5s
      retries: 3
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password123!"

volumes:
  mssql22:
