version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "sqlserver"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - "sqlserver"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    shm_size: 1gb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mssql22:/var/opt/mssql
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password123!"

volumes:
  mssql22:
