version: '3.4'

services:
  healthcheck.testingwebapp:
    image: ${DOCKER_REGISTRY-}healthchecktestingwebapp
    build:
      context: ../..
      dockerfile: src/HealthCheck/tests/TestingWebApp/Dockerfile
    healthcheck:
      test: [
        "CMD",
        "dotnet",
        "HealthCheck.Console.dll",
        "http://localhost:8080/healthz"
      ]
      interval: 5s
      timeout: 30s
      retries: 1
      start_period: 5s
