version: '3.4'

services:
  healthcheck.testingwebapp:
    image: ${DOCKER_REGISTRY-}healthchecktestingwebapp
    build:
      context: ../..
      dockerfile: src/HealthCheck/tests/TestingWebApp/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1000:80"
      - "1001:443"
    healthcheck:
      test: [
        "CMD",
        "dotnet",
        "HealthCheck.Console.dll",
        "http://localhost:80/healthz"
      ]
      interval: 5s
      timeout: 30s
      retries: 1
      start_period: 5s

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    shm_size: 1gb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - mssql22:/var/opt/mssql
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password123!"

volumes:
  mssql22:
