name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/dotnet-tools.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies
      run: |
        dotnet restore ./ContainizationStarter.sln --locked-mode
        dotnet tool restore

    - name: Build
      run: dotnet build ./ContainizationStarter.sln -c Release --no-restore

    - name: Format Checking
      run: dotnet format ./ContainizationStarter.sln --no-restore --verify-no-changes -v diag

    - name: Test
      run:  dotnet test ./ContainizationStarter.sln -c Release --no-build --verbosity normal --filter FullyQualifiedName!~AcceptanceTests
